table:
  name: e_timeout_settings
  schema: public
is_enum: true
select_permissions:
  - role: guest
    permission:
      columns:
        - description
        - value
      filter: {}
    comment: ""
