table:
  name: settings
  schema: public
insert_permissions:
  - role: administrator
    permission:
      check: {}
      columns:
        - name
        - value
    comment: ""
select_permissions:
  - role: administrator
    permission:
      columns:
        - name
        - value
      filter: {}
    comment: ""
  - role: guest
    permission:
      columns:
        - name
        - value
      filter:
        name:
          _like: public.%
    comment: ""
update_permissions:
  - role: administrator
    permission:
      columns:
        - name
        - value
      filter: {}
      check: {}
    comment: ""
delete_permissions:
  - role: administrator
    permission:
      filter: {}
    comment: ""
event_triggers:
  - name: settings
    definition:
      delete:
        columns: '*'
      enable_manual: false
      insert:
        columns: '*'
      update:
        columns: '*'
    retry_conf:
      interval_sec: 10
      num_retries: 0
      timeout_sec: 60
    webhook: '{{HASURA_GRAPHQL_EVENT_HOOK}}'
